version: '3.4'

services:
  eftest:
    image: ${DOCKER_REGISTRY-}eftest
    build:
      context: .
      dockerfile: EFTest/Dockerfile

  postgres:
    image: postgres:11.2-alpine
    shm_size: 256M
    ports:
      - 5432:5432
    volumes:
      - pg_auth_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"

volumes:
  pg_auth_data:
  pgadmin: